### ISSUE TITLE
Change the listener to a visitor?

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon.tool.converter.java2ceylon#1]
ANTLR ASTs can be inspected by [listeners](https://theantlrguy.atlassian.net/wiki/display/ANTLR4/Parse+Tree+Listeners) or visitors (like the ones we have in ceylon-spec). ANTLR generates an empty implementation for both, that we just need to extend to do whatever we have to do. Listeners consist of pairs of methods for each rule in the grammar: `enterRuleXyz()` and `exitRuleXyz()`.

The [current implementation](https://github.com/ceylon/ceylon.tool.converter.java2ceylon/blob/aeedd88095b25d4de49b8895e4d2e2bd01b4afff/source/ceylon/tool/converter/java2ceylon/JavaToCeylonConverter.java) is based on a listener, but in my opinion it introduces a lot of difficulty to convert "complex" cases, as it requires us to maintain _a lot_ of states (currently we have about 20 boolean flags and about 12 `String`s, all of which are used to determine the current state).

This complexity will grow when we will add support for more complex expressions such as `foo.getBar().getBaz()` (converted to `foo.bar.baz`), `new AnonymousClass() { ... }.instanceMethod()` etc.

I suggest we switch to a visitor instead. This way, we will be in control of _when_ methods are called, which means we will always know what the current context is. 

Consider the following case:

```
new Object() {}.toString();
```

The current converter assumes invocations are always of the form `identifer.identifier()`, so it copies everything it finds until the first dot, then prints a dot, then the method name, the parameters etc. For the previous code, `enterMethodInvocation()` will thus produce

```
newObject(){}.toString() // notice how the spaces were stripped
```

But wait, its not finished! The parser will detect that the left part of the invocation is a new instance, so `enterClassInstanceCreationExpression()` will kick in and... transform the left part once again, this time correctly. We end up with this:

```
newObject(){}.toString()object satisfies Object{
}
```

While I'm sure this is fixable in the current implementation, I'm not sure it will be straightforward (I will likely add more flags to detect the current state).

Compare this with a Visitor-based approach:

```
void visitMethodInvocation() {
  visitPrimary();
  print(".");
  visitIdentifier();
  print("(");
  visitArgumentList();
  print(")");
}
```

Whatever `primary` the left part of the invocation is, it will be handled correctly, as long as we override the correct `visitXxx()` method. No state to store.

I'm deeply convinced that switching to a visitor will bring us a clean and maintainable codebase that will
allow us to easily add missing constructs, and add options to transform `getX()` to `x` for example.

A few weeks ago I rewrote this listener to a visitor. This resulted in ~1400 LoC instead of the current 3500, 0 flag to store the current context, and every unit test green except one. It also transforms getters to properties, adds an option to create non-`variable` parameters, and handles things like invocations on anonymous classes.

If you guys think this is a  good idea, I'd like to integrate the latest changes in my visitor (mainly the support for `enum`s), and push it here to be used instead of the listener.

Having a reliable code converter would be a **huge** benefit for David and I, because we are currently migrating _a lot_ of Java code from ceylon-ide-eclipse to ceylon-ide-common.

**Comment by FroMage** [comment]
That seems fine by me.

**Comment by gavinking** [comment]
Well, sure, we use visitors in the compiler for walking our AST.

**Comment by rohitmohan96** [comment]
Fine with me.

**Comment by bjansen** [comment]
Done in 8df24d46436f03706855d267477ab0b5ed7cd5b5
