### ISSUE TITLE
handle Foo.class

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon.tool.converter.java2ceylon#14]
Accesses to `.class` members are removed in the generated code, instead they should be transformed to calls to `javaClass<Foo>()`.

**Comment by rohitmohan96** [comment]
@bjansen What is `javaClass` exactly?

**Comment by bjansen** [comment]
It's a [function located in ceylon.interop.java](https://modules.ceylon-lang.org/repo/1/ceylon/interop/java/1.2.1/module-doc/api/index.html#javaClass).

**Comment by rohitmohan96** [comment]
Thanks.
