### ISSUE TITLE
treat calls to setter methods as assignment

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon.tool.converter.java2ceylon#20]
Obviously this not _always_ going to be correct, since setters with no matching getter are treated by our model loader as methods, not as attributes, but I think it's probably better if we transform calls of form `setFoo(x)` as assignments `foo = x`.

**Comment by rohitmohan96** [comment]
Isn't this same as #3 ?

**Comment by gavinking** [comment]
Yes, sure, of course. Sorry.
