### ISSUE TITLE
transform a list of statements

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon.tool.converter.java2ceylon#22]
java2ceylon can currently cope with a whole method or class, but doesn't like it if I copy/paste a list of statements. It seems to me that it would not be that hard to do the following:
1. first, try to parse the fragment as a (list of?) methods or classes, and
2. if that fails, try again to parse it as a list of statements.

WDYT, @rohitmohan96 ?

**Comment by rohitmohan96** [comment]
I think this is related to #16. To get methods working @bjansen had to modify the grammar.

**Comment by gavinking** [comment]
Well typically ANTLR grammars can start parsing at any one of their rules. You don't _have_ to start at the toplevel rule. That's why I suggested the strategy above.

**Comment by gavinking** [comment]
Well, OTOH, we can introduce a new toplevel rule like this:

``` antlr
fragment: class | method+ | statement+;
```

And always start parsing from that rule.

As written, it's ambiguous, since classes are legal statements in Java, but it should be easy to disambiguate that.

**Comment by rohitmohan96** [comment]
I have modified the grammar to allow statements along with methods in 883ef8061b31f87749572805741994e730ca0f4a. I have noted the changes made [here](https://github.com/ceylon/ceylon.tool.converter.java2ceylon/blob/master/grammar/CHANGES.md).

**Comment by gavinking** [comment]
@rohitmohan96 Awesome! That's fantastic, thanks.

**Comment by rohitmohan96** [comment]
Closing this and #16.
