### ISSUE TITLE
handle lambdas

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon.tool.converter.java2ceylon#23]
Currently java2ceylon ignores the parameter list of a Java lambda expression. Now that we have support for SAM conversions, all it needs to do is transform a skinny arrow into a fat arrow. This should be a pretty easy fix.

**Comment by rohitmohan96** [comment]
Added lambdas in 812fbc67729b2f. Is this enough? I am yet to add tests.

**Comment by bjansen** [comment]
@rohitmohan96 I fixed the conversion to not add a fat arrow when there's already a block (otherwise, it'd be a fat arrow returning a stream). I also added tests, because we need that feature in the upcoming 1.3.1 release.

**Comment by rohitmohan96** [comment]
@bjansen I fixed the single identifier conversion and the test in b22c7f707858ecca96.

**Comment by gavinking** [comment]
Thanks folks!
