### ISSUE TITLE
handle static imports

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon.tool.converter.java2ceylon#32]
The converter doesn't correctly handle Java `static import`s.

**Comment by rohitmohan96** [comment]
https://github.com/ceylon/ceylon.tool.converter.java2ceylon/issues/13 Wasn't this fixed already?

**Comment by gavinking** [comment]
@rohitmohan96 Doesn't seem to be. When the tool encounters a static import like this:

    import static foo.bar.Baz.whatever;

It seems to generate this:

    import foo.bar.Baz { whatever }

It should be:

    import foo.bar { Baz { whatever } }

and indeed the static import should be collected together with other imports from `foo.bar`.

**Comment by rohitmohan96** [comment]
For 
```java
import static foo.bar.Baz.whatever;
import foo.bar.Bar;
```

I get
```ceylon
import foo.bar {
Baz{
whatever
}
,
Bar
}
```

when I run it from the converter from the cli.

**Comment by gavinking** [comment]
Hrm. I wonder why that did not work for me...

**Comment by gavinking** [comment]
Alight, I can't reproduce this problem right now, it must have been in some rather special case. Closing for now. I'll reopen if/when I can reproduce it.
