### ISSUE TITLE
don't use 'value' for field initialized to null

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon.tool.converter.java2ceylon#40]
It's not ucommon to find code like this in Java:

    Whatever whatever = null;

Currently that code gets translated to this:

    value whatever = null;

Which is certainly wrong. We should leave the type in when the variable is initialized to null.

**Comment by rohitmohan96** [comment]
Should be fixed now.

**Comment by gavinking** [comment]
Thanks!
