### ISSUE TITLE
mark value variable only when necessary

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon.tool.converter.java2ceylon#6]
Currently, the converter marks everything `variable` that is not explicitly declared `final` in Java. That results in _way_ too many `variable` annotations including on things like parameters.

We should add two separate phases (AST visitors) that:
1. build up a tree of scopes and model objects for declarations, and 
2. mark values which are actually re-assigned.

Then only values which are assigned somewhere, or which are non-`private` class members would need to be marked `variable`.

This probably sounds like a lot of work but in fact I think it's quite straightforward, and it lays the necessary foundation for making a number of other important improvements to the converter.

@rohitmohan96 are you interested in starting work on this?

**Comment by bjansen** [comment]
Oh, I forgot to document this, but you can already configure that in `.ceylon/ide-config`:

```
[converter]
use-values=true
use-variable-in-locals=false
transform-getters=true
use-variable-in-parameters=false
```

But if `use-variable-in-locals=false`, it will generate errors if the value is reassigned.

**Comment by bjansen** [comment]
If we add such visitors, I think it would make sense to force optional types if we detect that null is assigned. Currently, `use-values=true` converts types to `value` if there's a direct assignment:

```
value a = 1;
Integer b; // no value here
b = 2;
```

But it fails with code like

```
value a = "hello";
...
a = null;
```

**Comment by tombentley** [comment]
> ```
> [converter]
> ```

This is an aside: we obsessed about the package name for this thing, and settled on the ugly `...java2ceylon`, but don't apply any consistency to the naming of the config section.might

**Comment by rohitmohan96** [comment]
I have exams this week, so I can start working on it this Saturday.

**Comment by gavinking** [comment]
> I have exams this week, so I can start working on it this Saturday.

Awesome! :-)

**Comment by gavinking** [comment]
> but don't apply any consistency to the naming of the config section.

So open an issue @tombentley.

**Comment by gavinking** [comment]
> I think it would make sense to force optional types if we detect that null is assigned.

@bjansen _Definitely_. Yeah, so that's something that could be handled here at the same time as `variable`.

Note that we should also infer that a field of a class is nullable if it is never assigned by any constructor, nor in its definition.

**Comment by rohitmohan96** [comment]
Sorry I can't start working on this now, I have some college work to do. I'll get back to this as soon as possible.

**Comment by rohitmohan96** [comment]
I have added this in e801687. Since, it marks values as `variable` only when necessary, are the `useVariableInParams` and  `useVariableInLocals` flags required?

**Comment by bjansen** [comment]
I think we can remove them once we've tested your work ;)

**Comment by bjansen** [comment]
So I've been using the converter a lot in the past few months, and I think we're good with `variable` values. There's still some cases where it's not necessary, but those cases might not be easy to detect:

``` ceylon
variable String a;

if (condition) {
    a = "1";
} else {
    a = "2";
}
```

In this case, `variable` is not necessary because `a` is assigned only once, but it might be more difficult to detect this:

``` ceylon
variable String a;

if (condition) {
    a = "1";
    ...
    if (otherCondition) {
        a = "3";
    }
} else {
    a = "2";
}
```

So I think the current behavior is good enough. @rohitmohan96 I you have some free time, I think you can remove `useVariableInParams` and `useVariableInLocals`. Thanks.

**Comment by rohitmohan96** [comment]
I have removed `useVariableInParams` and `useVariableInLocals` in 0969e07.

**Comment by rohitmohan96** [comment]
I have added optional types in 53e0936. Closing for now.
