### ISSUE TITLE
java2ceylon can't convert enums

### ISSUE THREAD

**Issue by lukedegruchy** [ceylon/ceylon.tool.converter.java2ceylon#8]
Converting a Java enum results in Java code that does not compile:

Java enum:

``` java
private enum TheRoyalWe {
    ME, MYSELF, I;
}
```

Resulting Ceylon:

``` ceylon
class TheRoyalWe {
    shared actual String string;
    shared \iME {
        string = "ME";
    }

    shared \iMYSELF {
        string = "MYSELF";
    }

    shared \iI {
        string = "I";
    }
}
```

**Comment by gavinking** [comment]
@rohitmohan96 would you take a look, please?

**Comment by rohitmohan96** [comment]
It seems to work for me. 
I get 

``` ceylon
class TheRoyalWe {
    shared actual String string;
    shared new \iME { string = "ME"; }
    shared new \iMYSELF { string = "MYSELF"; }
    shared new \iI { string = "I"; }
}
```

when I convert.

**Comment by rohitmohan96** [comment]
Oh wait, but that's not what I get when I paste it in the IDE...

**Comment by rohitmohan96** [comment]
It looks like it has something to do with the `format()` method in `PasteAsCeylonHandler`.

**Comment by gavinking** [comment]
Aha, so it's a bug in `ceylon.format`, perhaps. That makes sense to me, after looking at the code. @lucaswerkmeister?

**Comment by lucaswerkmeister** [comment]
I’ll have a look

**Comment by lucaswerkmeister** [comment]
Should be fixed, formatter was missing support for value constructors.

**Comment by gavinking** [comment]
Thanks, @lucaswerkmeister!

**Comment by lukedegruchy** [comment]
Confirmed!

**Comment by lucaswerkmeister** [comment]
Oh, and by the way @gavinking: I just realized that this illustrates another difference between passing a token stream to the formatter, and not passing one (`null`). With token stream, the formatter would have detected an unaccounted for `new` token, and would have thrown an error.
